name: RunTests

on:
  push:
    branches: [ new_features_311614 ]
  workflow_dispatch:

jobs:
  unittest:
    name: Running unittests on ${{ matrix.os }} for file ${{ matrix.file }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        file: ['circle.py']
        os: [windows-latest]
    
    steps:  
     - name: Install Cache
       uses: actions/cache@v4.1.2
     - name: Install Python
       uses: actions/setup-python@v5.3.0


     - name: Test File
       run: python -m unittest .\${{ matrix.file }}
